
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.gates.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.gates.item.TheBrinkItem;
import net.mcreator.gates.item.Tainted_crystalSwordItem;
import net.mcreator.gates.item.Tainted_crystalShovelItem;
import net.mcreator.gates.item.Tainted_crystalPickaxeItem;
import net.mcreator.gates.item.Tainted_crystalHoeItem;
import net.mcreator.gates.item.Tainted_crystalDustItem;
import net.mcreator.gates.item.Tainted_crystalAxeItem;
import net.mcreator.gates.item.Tainted_crystalArmorItem;
import net.mcreator.gates.item.Shadow_stoneSwordItem;
import net.mcreator.gates.item.Shadow_stoneShovelItem;
import net.mcreator.gates.item.Shadow_stonePickaxeItem;
import net.mcreator.gates.item.Shadow_stoneIngotItem;
import net.mcreator.gates.item.Shadow_stoneHoeItem;
import net.mcreator.gates.item.Shadow_stoneAxeItem;
import net.mcreator.gates.item.Shadow_stoneArmorItem;
import net.mcreator.gates.item.CursedtoolsSwordItem;
import net.mcreator.gates.item.CursedtoolsShovelItem;
import net.mcreator.gates.item.CursedtoolsPickaxeItem;
import net.mcreator.gates.item.CursedtoolsHoeItem;
import net.mcreator.gates.item.CursedtoolsAxeItem;
import net.mcreator.gates.item.CursedsharedItem;
import net.mcreator.gates.item.CursedraworeItem;
import net.mcreator.gates.item.CursedcoreItem;
import net.mcreator.gates.item.CursedarmorArmorItem;
import net.mcreator.gates.item.Cursed_metalSwordItem;
import net.mcreator.gates.item.Cursed_metalShovelItem;
import net.mcreator.gates.item.Cursed_metalPickaxeItem;
import net.mcreator.gates.item.Cursed_metalIngotItem;
import net.mcreator.gates.item.Cursed_metalHoeItem;
import net.mcreator.gates.item.Cursed_metalAxeItem;
import net.mcreator.gates.item.Cursed_metalArmorItem;
import net.mcreator.gates.item.CursedRealmItem;
import net.mcreator.gates.item.CursedIngotItem;
import net.mcreator.gates.item.Curropted_toolsSwordItem;
import net.mcreator.gates.item.Curropted_toolsShovelItem;
import net.mcreator.gates.item.Curropted_toolsPickaxeItem;
import net.mcreator.gates.item.Curropted_toolsHoeItem;
import net.mcreator.gates.item.Curropted_toolsAxeItem;
import net.mcreator.gates.item.Curropted_armorArmorItem;
import net.mcreator.gates.item.CurroptedItem;
import net.mcreator.gates.GatesMod;

public class GatesModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, GatesMod.MODID);
	public static final RegistryObject<Item> CURSED_PORTALBLOCK = block(GatesModBlocks.CURSED_PORTALBLOCK);
	public static final RegistryObject<Item> CURSEDSHARED = REGISTRY.register("cursedshared", () -> new CursedsharedItem());
	public static final RegistryObject<Item> CURSEDCORE = REGISTRY.register("cursedcore", () -> new CursedcoreItem());
	public static final RegistryObject<Item> CURSEDGRASS = block(GatesModBlocks.CURSEDGRASS);
	public static final RegistryObject<Item> CURSEDDIRT = block(GatesModBlocks.CURSEDDIRT);
	public static final RegistryObject<Item> CURSEDCOBBLESTONE = block(GatesModBlocks.CURSEDCOBBLESTONE);
	public static final RegistryObject<Item> CURSEDARMOR_ARMOR_HELMET = REGISTRY.register("cursedarmor_armor_helmet", () -> new CursedarmorArmorItem.Helmet());
	public static final RegistryObject<Item> CURSEDARMOR_ARMOR_CHESTPLATE = REGISTRY.register("cursedarmor_armor_chestplate", () -> new CursedarmorArmorItem.Chestplate());
	public static final RegistryObject<Item> CURSEDARMOR_ARMOR_LEGGINGS = REGISTRY.register("cursedarmor_armor_leggings", () -> new CursedarmorArmorItem.Leggings());
	public static final RegistryObject<Item> CURSEDARMOR_ARMOR_BOOTS = REGISTRY.register("cursedarmor_armor_boots", () -> new CursedarmorArmorItem.Boots());
	public static final RegistryObject<Item> CURSEDSTONE = block(GatesModBlocks.CURSEDSTONE);
	public static final RegistryObject<Item> CURSED_ORE = block(GatesModBlocks.CURSED_ORE);
	public static final RegistryObject<Item> CURSED_BLOCK = block(GatesModBlocks.CURSED_BLOCK);
	public static final RegistryObject<Item> CURSED_INGOT = REGISTRY.register("cursed_ingot", () -> new CursedIngotItem());
	public static final RegistryObject<Item> CURSEDTOOLS_AXE = REGISTRY.register("cursedtools_axe", () -> new CursedtoolsAxeItem());
	public static final RegistryObject<Item> CURSEDTOOLS_PICKAXE = REGISTRY.register("cursedtools_pickaxe", () -> new CursedtoolsPickaxeItem());
	public static final RegistryObject<Item> CURSEDTOOLS_SWORD = REGISTRY.register("cursedtools_sword", () -> new CursedtoolsSwordItem());
	public static final RegistryObject<Item> CURSEDTOOLS_SHOVEL = REGISTRY.register("cursedtools_shovel", () -> new CursedtoolsShovelItem());
	public static final RegistryObject<Item> CURSEDTOOLS_HOE = REGISTRY.register("cursedtools_hoe", () -> new CursedtoolsHoeItem());
	public static final RegistryObject<Item> CURSEDRAWORE = REGISTRY.register("cursedrawore", () -> new CursedraworeItem());
	public static final RegistryObject<Item> CURROPTED_ORE = block(GatesModBlocks.CURROPTED_ORE);
	public static final RegistryObject<Item> CURROPTED_BLOCK = block(GatesModBlocks.CURROPTED_BLOCK);
	public static final RegistryObject<Item> CURROPTED = REGISTRY.register("curropted", () -> new CurroptedItem());
	public static final RegistryObject<Item> CURROPTED_ARMOR_ARMOR_HELMET = REGISTRY.register("curropted_armor_armor_helmet", () -> new Curropted_armorArmorItem.Helmet());
	public static final RegistryObject<Item> CURROPTED_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("curropted_armor_armor_chestplate", () -> new Curropted_armorArmorItem.Chestplate());
	public static final RegistryObject<Item> CURROPTED_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("curropted_armor_armor_leggings", () -> new Curropted_armorArmorItem.Leggings());
	public static final RegistryObject<Item> CURROPTED_ARMOR_ARMOR_BOOTS = REGISTRY.register("curropted_armor_armor_boots", () -> new Curropted_armorArmorItem.Boots());
	public static final RegistryObject<Item> CURROPTED_TOOLS_PICKAXE = REGISTRY.register("curropted_tools_pickaxe", () -> new Curropted_toolsPickaxeItem());
	public static final RegistryObject<Item> CURROPTED_TOOLS_AXE = REGISTRY.register("curropted_tools_axe", () -> new Curropted_toolsAxeItem());
	public static final RegistryObject<Item> CURROPTED_TOOLS_SWORD = REGISTRY.register("curropted_tools_sword", () -> new Curropted_toolsSwordItem());
	public static final RegistryObject<Item> CURROPTED_TOOLS_SHOVEL = REGISTRY.register("curropted_tools_shovel", () -> new Curropted_toolsShovelItem());
	public static final RegistryObject<Item> CURROPTED_TOOLS_HOE = REGISTRY.register("curropted_tools_hoe", () -> new Curropted_toolsHoeItem());
	public static final RegistryObject<Item> CURSEDSAND = block(GatesModBlocks.CURSEDSAND);
	public static final RegistryObject<Item> CURSED_WOOD = block(GatesModBlocks.CURSED_WOOD);
	public static final RegistryObject<Item> CURSED_LOG = block(GatesModBlocks.CURSED_LOG);
	public static final RegistryObject<Item> CURSED_PLANKS = block(GatesModBlocks.CURSED_PLANKS);
	public static final RegistryObject<Item> CURSED_LEAVES = block(GatesModBlocks.CURSED_LEAVES);
	public static final RegistryObject<Item> CURSED_STAIRS = block(GatesModBlocks.CURSED_STAIRS);
	public static final RegistryObject<Item> CURSED_SLAB = block(GatesModBlocks.CURSED_SLAB);
	public static final RegistryObject<Item> CURSED_FENCE = block(GatesModBlocks.CURSED_FENCE);
	public static final RegistryObject<Item> CURSED_FENCE_GATE = block(GatesModBlocks.CURSED_FENCE_GATE);
	public static final RegistryObject<Item> CURSED_PRESSURE_PLATE = block(GatesModBlocks.CURSED_PRESSURE_PLATE);
	public static final RegistryObject<Item> CURSED_BUTTON = block(GatesModBlocks.CURSED_BUTTON);
	public static final RegistryObject<Item> TAINTED_OAK_WOOD = block(GatesModBlocks.TAINTED_OAK_WOOD);
	public static final RegistryObject<Item> TAINTED_OAK_LOG = block(GatesModBlocks.TAINTED_OAK_LOG);
	public static final RegistryObject<Item> TAINTED_OAK_PLANKS = block(GatesModBlocks.TAINTED_OAK_PLANKS);
	public static final RegistryObject<Item> TAINTED_OAK_LEAVES = block(GatesModBlocks.TAINTED_OAK_LEAVES);
	public static final RegistryObject<Item> TAINTED_OAK_STAIRS = block(GatesModBlocks.TAINTED_OAK_STAIRS);
	public static final RegistryObject<Item> TAINTED_OAK_SLAB = block(GatesModBlocks.TAINTED_OAK_SLAB);
	public static final RegistryObject<Item> TAINTED_OAK_FENCE = block(GatesModBlocks.TAINTED_OAK_FENCE);
	public static final RegistryObject<Item> TAINTED_OAK_FENCE_GATE = block(GatesModBlocks.TAINTED_OAK_FENCE_GATE);
	public static final RegistryObject<Item> TAINTED_OAK_PRESSURE_PLATE = block(GatesModBlocks.TAINTED_OAK_PRESSURE_PLATE);
	public static final RegistryObject<Item> TAINTED_OAK_BUTTON = block(GatesModBlocks.TAINTED_OAK_BUTTON);
	public static final RegistryObject<Item> SOULWOOD_TREE_WOOD = block(GatesModBlocks.SOULWOOD_TREE_WOOD);
	public static final RegistryObject<Item> SOULWOOD_TREE_LOG = block(GatesModBlocks.SOULWOOD_TREE_LOG);
	public static final RegistryObject<Item> SOULWOOD_TREE_PLANKS = block(GatesModBlocks.SOULWOOD_TREE_PLANKS);
	public static final RegistryObject<Item> SOULWOOD_TREE_LEAVES = block(GatesModBlocks.SOULWOOD_TREE_LEAVES);
	public static final RegistryObject<Item> SOULWOOD_TREE_STAIRS = block(GatesModBlocks.SOULWOOD_TREE_STAIRS);
	public static final RegistryObject<Item> SOULWOOD_TREE_SLAB = block(GatesModBlocks.SOULWOOD_TREE_SLAB);
	public static final RegistryObject<Item> SOULWOOD_TREE_FENCE = block(GatesModBlocks.SOULWOOD_TREE_FENCE);
	public static final RegistryObject<Item> SOULWOOD_TREE_FENCE_GATE = block(GatesModBlocks.SOULWOOD_TREE_FENCE_GATE);
	public static final RegistryObject<Item> SOULWOOD_TREE_PRESSURE_PLATE = block(GatesModBlocks.SOULWOOD_TREE_PRESSURE_PLATE);
	public static final RegistryObject<Item> SOULWOOD_TREE_BUTTON = block(GatesModBlocks.SOULWOOD_TREE_BUTTON);
	public static final RegistryObject<Item> WRAITHWOOD_WOOD = block(GatesModBlocks.WRAITHWOOD_WOOD);
	public static final RegistryObject<Item> WRAITHWOOD_LOG = block(GatesModBlocks.WRAITHWOOD_LOG);
	public static final RegistryObject<Item> WRAITHWOOD_PLANKS = block(GatesModBlocks.WRAITHWOOD_PLANKS);
	public static final RegistryObject<Item> WRAITHWOOD_LEAVES = block(GatesModBlocks.WRAITHWOOD_LEAVES);
	public static final RegistryObject<Item> WRAITHWOOD_STAIRS = block(GatesModBlocks.WRAITHWOOD_STAIRS);
	public static final RegistryObject<Item> WRAITHWOOD_SLAB = block(GatesModBlocks.WRAITHWOOD_SLAB);
	public static final RegistryObject<Item> WRAITHWOOD_FENCE = block(GatesModBlocks.WRAITHWOOD_FENCE);
	public static final RegistryObject<Item> WRAITHWOOD_FENCE_GATE = block(GatesModBlocks.WRAITHWOOD_FENCE_GATE);
	public static final RegistryObject<Item> WRAITHWOOD_PRESSURE_PLATE = block(GatesModBlocks.WRAITHWOOD_PRESSURE_PLATE);
	public static final RegistryObject<Item> WRAITHWOOD_BUTTON = block(GatesModBlocks.WRAITHWOOD_BUTTON);
	public static final RegistryObject<Item> TAINTEDGRASS = block(GatesModBlocks.TAINTEDGRASS);
	public static final RegistryObject<Item> TAINTEDDIRT = block(GatesModBlocks.TAINTEDDIRT);
	public static final RegistryObject<Item> CURSED_REALM = REGISTRY.register("cursed_realm", () -> new CursedRealmItem());
	public static final RegistryObject<Item> CURROPTEDDIRT = block(GatesModBlocks.CURROPTEDDIRT);
	public static final RegistryObject<Item> CURROPTEDGRASS = block(GatesModBlocks.CURROPTEDGRASS);
	public static final RegistryObject<Item> SHADOW_STONE_ARMOR_HELMET = REGISTRY.register("shadow_stone_armor_helmet", () -> new Shadow_stoneArmorItem.Helmet());
	public static final RegistryObject<Item> SHADOW_STONE_ARMOR_CHESTPLATE = REGISTRY.register("shadow_stone_armor_chestplate", () -> new Shadow_stoneArmorItem.Chestplate());
	public static final RegistryObject<Item> SHADOW_STONE_ARMOR_LEGGINGS = REGISTRY.register("shadow_stone_armor_leggings", () -> new Shadow_stoneArmorItem.Leggings());
	public static final RegistryObject<Item> SHADOW_STONE_ARMOR_BOOTS = REGISTRY.register("shadow_stone_armor_boots", () -> new Shadow_stoneArmorItem.Boots());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_ARMOR_HELMET = REGISTRY.register("tainted_crystal_armor_helmet", () -> new Tainted_crystalArmorItem.Helmet());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_ARMOR_CHESTPLATE = REGISTRY.register("tainted_crystal_armor_chestplate", () -> new Tainted_crystalArmorItem.Chestplate());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_ARMOR_LEGGINGS = REGISTRY.register("tainted_crystal_armor_leggings", () -> new Tainted_crystalArmorItem.Leggings());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_ARMOR_BOOTS = REGISTRY.register("tainted_crystal_armor_boots", () -> new Tainted_crystalArmorItem.Boots());
	public static final RegistryObject<Item> CURSED_METAL_ARMOR_HELMET = REGISTRY.register("cursed_metal_armor_helmet", () -> new Cursed_metalArmorItem.Helmet());
	public static final RegistryObject<Item> CURSED_METAL_ARMOR_CHESTPLATE = REGISTRY.register("cursed_metal_armor_chestplate", () -> new Cursed_metalArmorItem.Chestplate());
	public static final RegistryObject<Item> CURSED_METAL_ARMOR_LEGGINGS = REGISTRY.register("cursed_metal_armor_leggings", () -> new Cursed_metalArmorItem.Leggings());
	public static final RegistryObject<Item> CURSED_METAL_ARMOR_BOOTS = REGISTRY.register("cursed_metal_armor_boots", () -> new Cursed_metalArmorItem.Boots());
	public static final RegistryObject<Item> SHADOW_STONE_ORE = block(GatesModBlocks.SHADOW_STONE_ORE);
	public static final RegistryObject<Item> SHADOW_STONE_BLOCK = block(GatesModBlocks.SHADOW_STONE_BLOCK);
	public static final RegistryObject<Item> TAINTED_CRYSTAL_ORE = block(GatesModBlocks.TAINTED_CRYSTAL_ORE);
	public static final RegistryObject<Item> TAINTED_CRYSTAL_BLOCK = block(GatesModBlocks.TAINTED_CRYSTAL_BLOCK);
	public static final RegistryObject<Item> CURSED_METAL_ORE = block(GatesModBlocks.CURSED_METAL_ORE);
	public static final RegistryObject<Item> CURSED_METAL_BLOCK = block(GatesModBlocks.CURSED_METAL_BLOCK);
	public static final RegistryObject<Item> SHADOW_STONE_INGOT = REGISTRY.register("shadow_stone_ingot", () -> new Shadow_stoneIngotItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_DUST = REGISTRY.register("tainted_crystal_dust", () -> new Tainted_crystalDustItem());
	public static final RegistryObject<Item> CURSED_METAL_INGOT = REGISTRY.register("cursed_metal_ingot", () -> new Cursed_metalIngotItem());
	public static final RegistryObject<Item> SHADOW_STONE_PICKAXE = REGISTRY.register("shadow_stone_pickaxe", () -> new Shadow_stonePickaxeItem());
	public static final RegistryObject<Item> SHADOW_STONE_AXE = REGISTRY.register("shadow_stone_axe", () -> new Shadow_stoneAxeItem());
	public static final RegistryObject<Item> SHADOW_STONE_SWORD = REGISTRY.register("shadow_stone_sword", () -> new Shadow_stoneSwordItem());
	public static final RegistryObject<Item> SHADOW_STONE_SHOVEL = REGISTRY.register("shadow_stone_shovel", () -> new Shadow_stoneShovelItem());
	public static final RegistryObject<Item> SHADOW_STONE_HOE = REGISTRY.register("shadow_stone_hoe", () -> new Shadow_stoneHoeItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_PICKAXE = REGISTRY.register("tainted_crystal_pickaxe", () -> new Tainted_crystalPickaxeItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_AXE = REGISTRY.register("tainted_crystal_axe", () -> new Tainted_crystalAxeItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_SWORD = REGISTRY.register("tainted_crystal_sword", () -> new Tainted_crystalSwordItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_SHOVEL = REGISTRY.register("tainted_crystal_shovel", () -> new Tainted_crystalShovelItem());
	public static final RegistryObject<Item> TAINTED_CRYSTAL_HOE = REGISTRY.register("tainted_crystal_hoe", () -> new Tainted_crystalHoeItem());
	public static final RegistryObject<Item> CURSED_METAL_PICKAXE = REGISTRY.register("cursed_metal_pickaxe", () -> new Cursed_metalPickaxeItem());
	public static final RegistryObject<Item> CURSED_METAL_AXE = REGISTRY.register("cursed_metal_axe", () -> new Cursed_metalAxeItem());
	public static final RegistryObject<Item> CURSED_METAL_SWORD = REGISTRY.register("cursed_metal_sword", () -> new Cursed_metalSwordItem());
	public static final RegistryObject<Item> CURSED_METAL_SHOVEL = REGISTRY.register("cursed_metal_shovel", () -> new Cursed_metalShovelItem());
	public static final RegistryObject<Item> CURSED_METAL_HOE = REGISTRY.register("cursed_metal_hoe", () -> new Cursed_metalHoeItem());
	public static final RegistryObject<Item> CURSEDDIORITE = block(GatesModBlocks.CURSEDDIORITE);
	public static final RegistryObject<Item> CURSEDANDISITE = block(GatesModBlocks.CURSEDANDISITE);
	public static final RegistryObject<Item> CURSEDGRANITE = block(GatesModBlocks.CURSEDGRANITE);
	public static final RegistryObject<Item> CURSEDBEING_SPAWN_EGG = REGISTRY.register("cursedbeing_spawn_egg", () -> new ForgeSpawnEggItem(GatesModEntities.CURSEDBEING, -10811641, -12581884, new Item.Properties()));
	public static final RegistryObject<Item> CURSEDWALKER_SPAWN_EGG = REGISTRY.register("cursedwalker_spawn_egg", () -> new ForgeSpawnEggItem(GatesModEntities.CURSEDWALKER, -7993850, -11599101, new Item.Properties()));
	public static final RegistryObject<Item> CURSEDSOUL_SPAWN_EGG = REGISTRY.register("cursedsoul_spawn_egg", () -> new ForgeSpawnEggItem(GatesModEntities.CURSEDSOUL, -16468799, -11163978, new Item.Properties()));
	public static final RegistryObject<Item> SHADOWMAN_SPAWN_EGG = REGISTRY.register("shadowman_spawn_egg", () -> new ForgeSpawnEggItem(GatesModEntities.SHADOWMAN, -10724260, -13487566, new Item.Properties()));
	public static final RegistryObject<Item> TAINTEDWALKER_SPAWN_EGG = REGISTRY.register("taintedwalker_spawn_egg", () -> new ForgeSpawnEggItem(GatesModEntities.TAINTEDWALKER, -12628424, -15129575, new Item.Properties()));
	public static final RegistryObject<Item> BRINKSAND = block(GatesModBlocks.BRINKSAND);
	public static final RegistryObject<Item> BRINKPORTAL = block(GatesModBlocks.BRINKPORTAL);
	public static final RegistryObject<Item> BRINKPORTALBLOCK = block(GatesModBlocks.BRINKPORTALBLOCK);
	public static final RegistryObject<Item> THE_BRINK = REGISTRY.register("the_brink", () -> new TheBrinkItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
