
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.gates.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.gates.block.WraithwoodWoodBlock;
import net.mcreator.gates.block.WraithwoodStairsBlock;
import net.mcreator.gates.block.WraithwoodSlabBlock;
import net.mcreator.gates.block.WraithwoodPressurePlateBlock;
import net.mcreator.gates.block.WraithwoodPlanksBlock;
import net.mcreator.gates.block.WraithwoodLogBlock;
import net.mcreator.gates.block.WraithwoodLeavesBlock;
import net.mcreator.gates.block.WraithwoodFenceGateBlock;
import net.mcreator.gates.block.WraithwoodFenceBlock;
import net.mcreator.gates.block.WraithwoodButtonBlock;
import net.mcreator.gates.block.TheBrinkPortalBlock;
import net.mcreator.gates.block.TaintedgrassBlock;
import net.mcreator.gates.block.TainteddirtBlock;
import net.mcreator.gates.block.Tainted_oakWoodBlock;
import net.mcreator.gates.block.Tainted_oakStairsBlock;
import net.mcreator.gates.block.Tainted_oakSlabBlock;
import net.mcreator.gates.block.Tainted_oakPressurePlateBlock;
import net.mcreator.gates.block.Tainted_oakPlanksBlock;
import net.mcreator.gates.block.Tainted_oakLogBlock;
import net.mcreator.gates.block.Tainted_oakLeavesBlock;
import net.mcreator.gates.block.Tainted_oakFenceGateBlock;
import net.mcreator.gates.block.Tainted_oakFenceBlock;
import net.mcreator.gates.block.Tainted_oakButtonBlock;
import net.mcreator.gates.block.Tainted_crystalOreBlock;
import net.mcreator.gates.block.Tainted_crystalBlockBlock;
import net.mcreator.gates.block.Soulwood_treeWoodBlock;
import net.mcreator.gates.block.Soulwood_treeStairsBlock;
import net.mcreator.gates.block.Soulwood_treeSlabBlock;
import net.mcreator.gates.block.Soulwood_treePressurePlateBlock;
import net.mcreator.gates.block.Soulwood_treePlanksBlock;
import net.mcreator.gates.block.Soulwood_treeLogBlock;
import net.mcreator.gates.block.Soulwood_treeLeavesBlock;
import net.mcreator.gates.block.Soulwood_treeFenceGateBlock;
import net.mcreator.gates.block.Soulwood_treeFenceBlock;
import net.mcreator.gates.block.Soulwood_treeButtonBlock;
import net.mcreator.gates.block.Shadow_stoneOreBlock;
import net.mcreator.gates.block.Shadow_stoneBlockBlock;
import net.mcreator.gates.block.CursedstoneBlock;
import net.mcreator.gates.block.CursedsandBlock;
import net.mcreator.gates.block.CursedgrassBlock;
import net.mcreator.gates.block.CursedgraniteBlock;
import net.mcreator.gates.block.CurseddirtBlock;
import net.mcreator.gates.block.CurseddioriteBlock;
import net.mcreator.gates.block.CursedcobblestoneBlock;
import net.mcreator.gates.block.CursedandisiteBlock;
import net.mcreator.gates.block.Cursed_metalOreBlock;
import net.mcreator.gates.block.Cursed_metalBlockBlock;
import net.mcreator.gates.block.CursedWoodBlock;
import net.mcreator.gates.block.CursedStairsBlock;
import net.mcreator.gates.block.CursedSlabBlock;
import net.mcreator.gates.block.CursedRealmPortalBlock;
import net.mcreator.gates.block.CursedPressurePlateBlock;
import net.mcreator.gates.block.CursedPortalblockBlock;
import net.mcreator.gates.block.CursedPlanksBlock;
import net.mcreator.gates.block.CursedOreBlock;
import net.mcreator.gates.block.CursedLogBlock;
import net.mcreator.gates.block.CursedLeavesBlock;
import net.mcreator.gates.block.CursedFenceGateBlock;
import net.mcreator.gates.block.CursedFenceBlock;
import net.mcreator.gates.block.CursedButtonBlock;
import net.mcreator.gates.block.CursedBlockBlock;
import net.mcreator.gates.block.CurroptedgrassBlock;
import net.mcreator.gates.block.CurropteddirtBlock;
import net.mcreator.gates.block.CurroptedOreBlock;
import net.mcreator.gates.block.CurroptedBlockBlock;
import net.mcreator.gates.block.BrinksandBlock;
import net.mcreator.gates.block.BrinkportalblockBlock;
import net.mcreator.gates.block.BrinkportalBlock;
import net.mcreator.gates.GatesMod;

public class GatesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, GatesMod.MODID);
	public static final RegistryObject<Block> CURSED_PORTALBLOCK = REGISTRY.register("cursed_portalblock", () -> new CursedPortalblockBlock());
	public static final RegistryObject<Block> CURSEDGRASS = REGISTRY.register("cursedgrass", () -> new CursedgrassBlock());
	public static final RegistryObject<Block> CURSEDDIRT = REGISTRY.register("curseddirt", () -> new CurseddirtBlock());
	public static final RegistryObject<Block> CURSEDCOBBLESTONE = REGISTRY.register("cursedcobblestone", () -> new CursedcobblestoneBlock());
	public static final RegistryObject<Block> CURSEDSTONE = REGISTRY.register("cursedstone", () -> new CursedstoneBlock());
	public static final RegistryObject<Block> CURSED_ORE = REGISTRY.register("cursed_ore", () -> new CursedOreBlock());
	public static final RegistryObject<Block> CURSED_BLOCK = REGISTRY.register("cursed_block", () -> new CursedBlockBlock());
	public static final RegistryObject<Block> CURROPTED_ORE = REGISTRY.register("curropted_ore", () -> new CurroptedOreBlock());
	public static final RegistryObject<Block> CURROPTED_BLOCK = REGISTRY.register("curropted_block", () -> new CurroptedBlockBlock());
	public static final RegistryObject<Block> CURSEDSAND = REGISTRY.register("cursedsand", () -> new CursedsandBlock());
	public static final RegistryObject<Block> CURSED_WOOD = REGISTRY.register("cursed_wood", () -> new CursedWoodBlock());
	public static final RegistryObject<Block> CURSED_LOG = REGISTRY.register("cursed_log", () -> new CursedLogBlock());
	public static final RegistryObject<Block> CURSED_PLANKS = REGISTRY.register("cursed_planks", () -> new CursedPlanksBlock());
	public static final RegistryObject<Block> CURSED_LEAVES = REGISTRY.register("cursed_leaves", () -> new CursedLeavesBlock());
	public static final RegistryObject<Block> CURSED_STAIRS = REGISTRY.register("cursed_stairs", () -> new CursedStairsBlock());
	public static final RegistryObject<Block> CURSED_SLAB = REGISTRY.register("cursed_slab", () -> new CursedSlabBlock());
	public static final RegistryObject<Block> CURSED_FENCE = REGISTRY.register("cursed_fence", () -> new CursedFenceBlock());
	public static final RegistryObject<Block> CURSED_FENCE_GATE = REGISTRY.register("cursed_fence_gate", () -> new CursedFenceGateBlock());
	public static final RegistryObject<Block> CURSED_PRESSURE_PLATE = REGISTRY.register("cursed_pressure_plate", () -> new CursedPressurePlateBlock());
	public static final RegistryObject<Block> CURSED_BUTTON = REGISTRY.register("cursed_button", () -> new CursedButtonBlock());
	public static final RegistryObject<Block> TAINTED_OAK_WOOD = REGISTRY.register("tainted_oak_wood", () -> new Tainted_oakWoodBlock());
	public static final RegistryObject<Block> TAINTED_OAK_LOG = REGISTRY.register("tainted_oak_log", () -> new Tainted_oakLogBlock());
	public static final RegistryObject<Block> TAINTED_OAK_PLANKS = REGISTRY.register("tainted_oak_planks", () -> new Tainted_oakPlanksBlock());
	public static final RegistryObject<Block> TAINTED_OAK_LEAVES = REGISTRY.register("tainted_oak_leaves", () -> new Tainted_oakLeavesBlock());
	public static final RegistryObject<Block> TAINTED_OAK_STAIRS = REGISTRY.register("tainted_oak_stairs", () -> new Tainted_oakStairsBlock());
	public static final RegistryObject<Block> TAINTED_OAK_SLAB = REGISTRY.register("tainted_oak_slab", () -> new Tainted_oakSlabBlock());
	public static final RegistryObject<Block> TAINTED_OAK_FENCE = REGISTRY.register("tainted_oak_fence", () -> new Tainted_oakFenceBlock());
	public static final RegistryObject<Block> TAINTED_OAK_FENCE_GATE = REGISTRY.register("tainted_oak_fence_gate", () -> new Tainted_oakFenceGateBlock());
	public static final RegistryObject<Block> TAINTED_OAK_PRESSURE_PLATE = REGISTRY.register("tainted_oak_pressure_plate", () -> new Tainted_oakPressurePlateBlock());
	public static final RegistryObject<Block> TAINTED_OAK_BUTTON = REGISTRY.register("tainted_oak_button", () -> new Tainted_oakButtonBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_WOOD = REGISTRY.register("soulwood_tree_wood", () -> new Soulwood_treeWoodBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_LOG = REGISTRY.register("soulwood_tree_log", () -> new Soulwood_treeLogBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_PLANKS = REGISTRY.register("soulwood_tree_planks", () -> new Soulwood_treePlanksBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_LEAVES = REGISTRY.register("soulwood_tree_leaves", () -> new Soulwood_treeLeavesBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_STAIRS = REGISTRY.register("soulwood_tree_stairs", () -> new Soulwood_treeStairsBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_SLAB = REGISTRY.register("soulwood_tree_slab", () -> new Soulwood_treeSlabBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_FENCE = REGISTRY.register("soulwood_tree_fence", () -> new Soulwood_treeFenceBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_FENCE_GATE = REGISTRY.register("soulwood_tree_fence_gate", () -> new Soulwood_treeFenceGateBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_PRESSURE_PLATE = REGISTRY.register("soulwood_tree_pressure_plate", () -> new Soulwood_treePressurePlateBlock());
	public static final RegistryObject<Block> SOULWOOD_TREE_BUTTON = REGISTRY.register("soulwood_tree_button", () -> new Soulwood_treeButtonBlock());
	public static final RegistryObject<Block> WRAITHWOOD_WOOD = REGISTRY.register("wraithwood_wood", () -> new WraithwoodWoodBlock());
	public static final RegistryObject<Block> WRAITHWOOD_LOG = REGISTRY.register("wraithwood_log", () -> new WraithwoodLogBlock());
	public static final RegistryObject<Block> WRAITHWOOD_PLANKS = REGISTRY.register("wraithwood_planks", () -> new WraithwoodPlanksBlock());
	public static final RegistryObject<Block> WRAITHWOOD_LEAVES = REGISTRY.register("wraithwood_leaves", () -> new WraithwoodLeavesBlock());
	public static final RegistryObject<Block> WRAITHWOOD_STAIRS = REGISTRY.register("wraithwood_stairs", () -> new WraithwoodStairsBlock());
	public static final RegistryObject<Block> WRAITHWOOD_SLAB = REGISTRY.register("wraithwood_slab", () -> new WraithwoodSlabBlock());
	public static final RegistryObject<Block> WRAITHWOOD_FENCE = REGISTRY.register("wraithwood_fence", () -> new WraithwoodFenceBlock());
	public static final RegistryObject<Block> WRAITHWOOD_FENCE_GATE = REGISTRY.register("wraithwood_fence_gate", () -> new WraithwoodFenceGateBlock());
	public static final RegistryObject<Block> WRAITHWOOD_PRESSURE_PLATE = REGISTRY.register("wraithwood_pressure_plate", () -> new WraithwoodPressurePlateBlock());
	public static final RegistryObject<Block> WRAITHWOOD_BUTTON = REGISTRY.register("wraithwood_button", () -> new WraithwoodButtonBlock());
	public static final RegistryObject<Block> TAINTEDGRASS = REGISTRY.register("taintedgrass", () -> new TaintedgrassBlock());
	public static final RegistryObject<Block> TAINTEDDIRT = REGISTRY.register("tainteddirt", () -> new TainteddirtBlock());
	public static final RegistryObject<Block> CURSED_REALM_PORTAL = REGISTRY.register("cursed_realm_portal", () -> new CursedRealmPortalBlock());
	public static final RegistryObject<Block> CURROPTEDDIRT = REGISTRY.register("curropteddirt", () -> new CurropteddirtBlock());
	public static final RegistryObject<Block> CURROPTEDGRASS = REGISTRY.register("curroptedgrass", () -> new CurroptedgrassBlock());
	public static final RegistryObject<Block> SHADOW_STONE_ORE = REGISTRY.register("shadow_stone_ore", () -> new Shadow_stoneOreBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BLOCK = REGISTRY.register("shadow_stone_block", () -> new Shadow_stoneBlockBlock());
	public static final RegistryObject<Block> TAINTED_CRYSTAL_ORE = REGISTRY.register("tainted_crystal_ore", () -> new Tainted_crystalOreBlock());
	public static final RegistryObject<Block> TAINTED_CRYSTAL_BLOCK = REGISTRY.register("tainted_crystal_block", () -> new Tainted_crystalBlockBlock());
	public static final RegistryObject<Block> CURSED_METAL_ORE = REGISTRY.register("cursed_metal_ore", () -> new Cursed_metalOreBlock());
	public static final RegistryObject<Block> CURSED_METAL_BLOCK = REGISTRY.register("cursed_metal_block", () -> new Cursed_metalBlockBlock());
	public static final RegistryObject<Block> CURSEDDIORITE = REGISTRY.register("curseddiorite", () -> new CurseddioriteBlock());
	public static final RegistryObject<Block> CURSEDANDISITE = REGISTRY.register("cursedandisite", () -> new CursedandisiteBlock());
	public static final RegistryObject<Block> CURSEDGRANITE = REGISTRY.register("cursedgranite", () -> new CursedgraniteBlock());
	public static final RegistryObject<Block> BRINKSAND = REGISTRY.register("brinksand", () -> new BrinksandBlock());
	public static final RegistryObject<Block> BRINKPORTAL = REGISTRY.register("brinkportal", () -> new BrinkportalBlock());
	public static final RegistryObject<Block> BRINKPORTALBLOCK = REGISTRY.register("brinkportalblock", () -> new BrinkportalblockBlock());
	public static final RegistryObject<Block> THE_BRINK_PORTAL = REGISTRY.register("the_brink_portal", () -> new TheBrinkPortalBlock());
}
